export { initializeDatabase, startDatabaseBackups, stopDatabaseBackups } from '@/modules/database/init-db.js';
export { backupDatabase, closeConnection, getConnection, getDatabasePath } from '@/modules/database/connection.js';
export { apiKeysDb } from '@/modules/database/repositories/api-keys.js';
export { auditLogDb } from '@/modules/database/repositories/audit-log.js';
export type { AuditEntry, AuditEvent, AuditRow } from '@/modules/database/repositories/audit-log.js';
export { appConfigDb } from '@/modules/database/repositories/app-config.js';
export { credentialsDb } from '@/modules/database/repositories/credentials.js';
export { githubTokensDb } from '@/modules/database/repositories/github-tokens.js';
export { notificationPreferencesDb } from '@/modules/database/repositories/notification-preferences.js';
export { projectsDb } from '@/modules/database/repositories/projects.db.js';
export { publishedPagesDb } from '@/modules/database/repositories/published-pages.js';
export type { PublicationKind, PublishedPageRow } from '@/modules/database/repositories/published-pages.js';
export { scanStateDb } from '@/modules/database/repositories/scan-state.db.js';
export { sessionsDb } from '@/modules/database/repositories/sessions.db.js';
export { userDb } from '@/modules/database/repositories/users.js';
export type { ApprovalStatus, UserAdminRow } from '@/modules/database/repositories/users.js';
