"""Generate executable contract tests from CONTRACT.yaml ``checks``.

Natural-language pre/postconditions are for humans. These are the subset G3 can
run: never_raises, returns_type, pure, idempotent, raises, example. They are
written to ``tests/contract/`` (regenerated every time, never hand-edited, never
touched by the optimizer) and executed by the contract gate.
"""
from __future__ import annotations

import re
from pathlib import Path

from .types import Contract, Entrypoint

HEADER = '''# GENERATED by skillwhet from CONTRACT.yaml — do not edit; regenerate.
import sys, pathlib, json
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))
import pytest
'''

_TYPES = {"list": "list", "dict": "dict", "str": "str", "int": "int",
          "bool": "bool", "float": "float", "None": "type(None)", "tuple": "tuple"}


def _mod(e: Entrypoint) -> str:
    return e.module.replace("/", ".").removesuffix(".py")


def _lit(v) -> str:
    """A Python literal, not JSON: None/True/False must not become null/true/false."""
    return repr(v)


def _callargs(spec: dict) -> str:
    args = spec.get("args") or []
    kwargs = spec.get("kwargs") or {}
    parts = [_lit(a) for a in args]
    parts += [f"{k}={_lit(v)}" for k, v in kwargs.items()]
    return ", ".join(parts)


def _ident(s: str) -> str:
    """Make any string safe inside a test function name."""
    return re.sub(r"\W", "_", s).strip("_") or "x"


def _slug(e: Entrypoint) -> str:
    return _ident(_mod(e).split(".", 1)[-1]) + "__" + _ident(e.id)


def render(e: Entrypoint) -> str:
    """One test module per entrypoint."""
    if not e.checks:
        return ""
    fn = _ident(e.id.split(".")[-1])
    lines = [HEADER, f"from {_mod(e)} import {e.id.split('.')[0]}", ""]
    target = e.id  # Class.method works via attribute chain
    for i, chk in enumerate(e.checks):
        if "never_raises" in chk:
            spec = chk["never_raises"] or {}
            lines += [f"def test_{fn}_never_raises_{i}():",
                      f"    {target}({_callargs(spec)})", ""]
        elif "returns_type" in chk:
            want = str(chk["returns_type"])
            t = _TYPES.get(want)
            spec = chk.get("with") or {}
            if t is None:
                # An unknown type must not vanish silently: emit a test that
                # fails loudly, so the contract author sees it at G3.
                msg = (f"CONTRACT.yaml: unknown returns_type {want!r}; "
                       f"use one of {sorted(_TYPES)}")
                lines += [f"def test_{fn}_returns_{_ident(want)}_{i}():",
                          f"    pytest.fail({msg!r})", ""]
            else:
                lines += [f"def test_{fn}_returns_{_ident(want)}_{i}():",
                          f"    assert isinstance({target}({_callargs(spec)}), {t})", ""]
        elif "pure" in chk:
            spec = chk["pure"] or {}
            lines += [f"def test_{fn}_pure_{i}():",
                      f"    a = {target}({_callargs(spec)})",
                      f"    b = {target}({_callargs(spec)})",
                      "    assert a == b", ""]
        elif "idempotent" in chk:
            spec = chk["idempotent"] or {}
            lines += [f"def test_{fn}_idempotent_{i}():",
                      f"    once = {target}({_callargs(spec)})",
                      f"    assert {target}(once) == once", ""]
        elif "raises" in chk:
            spec = chk["raises"] or {}
            exc = str(spec.get("exc", "Exception"))
            lines += [f"def test_{fn}_raises_{_ident(exc)}_{i}():",
                      f"    with pytest.raises({exc}):",
                      f"        {target}({_callargs(spec)})", ""]
        elif "example" in chk:
            # The one check kind that pins BEHAVIOUR, not just shape. It exists
            # because of a measured failure mode: when several candidates repair
            # the same tasks, the search's tie-break is the smallest diff, and
            # minimality is anti-correlated with generality (REVIEW §9.4). A
            # stated example makes the general case observable to the fast loop
            # at zero model cost — the maintainer writes down one case the
            # training tasks do not cover, and it becomes a G3 gate.
            spec = chk["example"] or {}
            if "returns" not in spec:
                msg = "CONTRACT.yaml: example check needs a 'returns' value"
                lines += [f"def test_{fn}_example_{i}():", f"    pytest.fail({msg!r})", ""]
            else:
                lines += [f"def test_{fn}_example_{i}():",
                          f"    assert {target}({_callargs(spec)}) == {_lit(spec['returns'])}", ""]
    return "\n".join(lines) + "\n" if len(lines) > 3 else ""


def generate(skill_dir: Path, contract: Contract) -> list[Path]:
    """(Re)write tests/contract/. Returns the files written."""
    out_dir = Path(skill_dir) / "tests" / "contract"
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.glob("test_contract_*.py"):
        old.unlink()
    written = []
    for e in contract.entrypoints:
        src = render(e)
        if not src:
            continue
        p = out_dir / f"test_contract_{_slug(e)}.py"
        p.write_text(src, encoding="utf-8")
        written.append(p)
    return written
